# Generated by Django 4.2.30 on 2026-06-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Lower')], max_length=20)),
                ('status', models.CharField(choices=[('in_store', 'In Store'), ('on_machine', 'On Machine'), ('processed', 'Processed'), ('sold', 'Sold')], default='in_store', max_length=20)),
                ('location', models.CharField(default='Main Store', max_length=100)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.delivery')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_contact', models.CharField(max_length=50)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('coffee_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.coffeebatch')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeProcessingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('pulping', 'Pulping'), ('fermenting', 'Fermenting'), ('washing', 'Washing'), ('drying', 'Drying'), ('hulling', 'Hulling'), ('grading', 'Grading')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('coffee_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.coffeebatch')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
